### ISSUE TITLE
Memory Overflow Issues with Different Image Sizes during Inference

### ISSUE THREAD

**Issue by song-wensong** [lsl001006/ZONE#6]
Hello,

I have encountered a memory overflow issue during inference with your model and would appreciate some insights.

When using 512x512 images, the process consumes approximately 22GB of GPU memory, which works fine. However, when I switch to an image of size 615x913, I experience out-of-memory errors. Assuming the error was due to the larger size, I resized the image to maintain a similar aspect ratio, making the longest side 512 pixels, resulting in an image size of 341x512. Surprisingly, this still resulted in a memory overflow.

Could you please help me understand why resizing the image to a smaller size does not mitigate the memory usage as expected? What factors could be contributing to this issue, and how might it be resolved?

Thank you for your assistance!

I apologize for the inconvenience, but I accidentally posted the same issue twice. Could you please help by deleting the duplicate?

**Comment by lsl001006** [comment]
Hi!

Thank you for reporting this issue and apologies for the delayed response.

The issue stems from **a size misalignment between two types of masks** in our pipeline:
- The attention-generated mask (which requires dimensions to be multiples of 32)
- The SAM-generated mask (which maintains the original aspect ratio)

We reproduced your scenario using our test image data/corgi.jpg. The results showed that the attention-generated mask had dimensions of (336,512), while the SAM-generated mask was (341,512). This discrepancy occurs due to the ceil function implementation in `line 36 of msk_from_attn.py`.

We've made the necessary modifications to the repository to ensure proper size alignment and prevent similar memory overflow problems. These changes should now handle images with various aspect ratios and dimensions. Please let us know if you encounter any further issues.

Best regards

**Comment by song-wensong** [comment]
Thank you for your detailed response and the efforts to fix the issue.

I’ve noticed that the out-of-memory (OOM) issue I’m encountering occurs before reaching the show_all_cross_attention function. Specifically, it happens at this line in the code: https://github.com/lsl001006/ZONE/blob/main/null_text_w_ptp.py#L1027.

I haven’t yet reached the point where the modified alignment in your update could affect execution. Could there be another potential cause for the memory overflow at this earlier stage of the process? Any further insights you might provide would be greatly appreciated.

Thank you once again for your assistance.

**Comment by song-wensong** [comment]
I’ve figured out the reason for the issue. On one hand, it’s because I was inputting PNG images with RGBA channels. On the other hand, when resizing the images, it is necessary to ensure that the dimensions are multiples of 32.
